### ISSUE TITLE
Bug in ds18b20_convert_and_read_temp

### ISSUE THREAD

**Issue by lightoze** [DavidAntliff/esp32-ds18b20#3]
`&temp` must be replaced with `value` here:
https://github.com/DavidAntliff/esp32-ds18b20/blob/0bb8f1b0cdca5f3acb12372e485e5126191052a2/ds18b20.c#L483

**Comment by DavidAntliff** [comment]
@lightoze yes, you're absolutely right and I will fix it. I have only been using `ds18b20_convert_all` so didn't come across this obvious bug. Thank you for letting me know.

**Comment by DavidAntliff** [comment]
Should be OK now - thanks again.
