### ISSUE TITLE
I find mixed return types DS18B20_ERROR and bool error-prone

### ISSUE THREAD

**Issue by pablobacho** [DavidAntliff/esp32-ds18b20#7]
Hi @DavidAntliff, I have a suggestion:

I find error-prone using two different return types, `bool` and `DS18B20_ERROR`, specially since their values mean the opposite of each other. Furthermore, the compiler doesn't even throw a warning if you check one against each other.

As an example, these 2 functions are normally used together but their return types are inconsistent:
```
bool ds18b20_convert(const DS18B20_Info * ds18b20_info);
DS18B20_ERROR ds18b20_read_temp(const DS18B20_Info * ds18b20_info, float * value);
```

I believe all `ds18b20` functions should use the `DS18B20_ERROR` return codes for code legibility (which I admit I am obsessed with). However, the change would potentially break existing code checking for true or false, since `DS18B20_OK == false`. If anything, I would change the value of `DS18B20_OK` to be 1 so it also equals true. That way the only code that would break is if it checks the return code just relying on it being `!= 0` or `!= false` in case of error.

If this is something you are willing to consider, I don't mind making the changes and doing a PR. What do you think?

Functionality-wise it works great. Thank you for sharing.

**Comment by DavidAntliff** [comment]
Hi @pablobacho - thank you for your comments. I'm glad the library works well for you.

To address your request: I'm reluctant to change the API just for stylistic reasons, however I do appreciate your concerns.

It is an ancient and very common convention that success codes have the value zero. This means that you test for success with the counter-intuitive `if (!some_func())...` however it is very common. I recommend instead using a style like `if (some_func() == DS18B20_ERROR) ...` instead, as it's more explicit and relies less on the value of `DS18B20_ERROR`. Unfortunately changing the value of that symbol to non-zero would break existing code that uses the former style. However I see how mixing the `bool` result style with this style could cause some nasty bugs.

The library actually changed at one point via another PR and that is where those error codes were introduced.

I wonder if the best approach might be to create new wrapping functions for ` ds18b20_read_temp` and `ds18b20_convert_and_read_temp` that return `bool` but also pass back the error code by reference. Something like `bool ds18b20_read_temp2(const DS18B20_Info * ds18b20_info, float * value, DS18B20_ERROR * err);` - that would allow the old functions to remain, but provide a cleaner API for new code.

The other option, which I might favour actually, is to convert *all* of the functions in the API to return a `DS18B20_ERROR` value, and anything else that might be returned is passed by pointer/reference.

I'll need to think about it a bit more, but please respond with your thoughts and comments.

**Comment by pablobacho** [comment]
It creates a bug that gets caught fairly quickly. I did it as soon as I opened the function to see when "error 1" was returned, and then I saw it was `true` and not "error 1". But it feels awkward to use different error-checking conventions within 3 lines of the same library.

I think they should all be either bool or DS18B20_ERROR. The functions affected are:

```
bool ds18b20_set_resolution(DS18B20_Info * ds18b20_info, DS18B20_RESOLUTION resolution);
bool ds18b20_convert(const DS18B20_Info * ds18b20_info);
DS18B20_ERROR ds18b20_read_temp(const DS18B20_Info * ds18b20_info, float * value);
DS18B20_ERROR ds18b20_convert_and_read_temp(const DS18B20_Info * ds18b20_info, float * value);
```

There is no need to change any other function. The rest return what they have to return, or void.

I would be more inclined to have the first two return `DS18B20_ERROR`, because I find useful knowing the reason for the error. But, like you said, it is so common that many programs probably check for `DS18B20_OK` with just `!` or check `true` by just calling the function in a condition, and changing them either way would break somebody's code.

I don't see the need to pass the error code by reference. I like the idea of a wrapper function, but I wonder if having two functions doing the same is going to be even more confusing for newcomers. If we can clearly state the difference (or similarities) between the two, wrapper functions sound to me like the best way to go.

This could also be postponed for a future non-backwards-compatible version of the library, since it is not critical.

**Comment by DavidAntliff** [comment]
Realistically I'll probably have to postpone this for now, other things need my attention, however the API is small enough that you could easily wrap it for your own purposes in the meantime. If at some point you'd like to contribute your wrapper (even for review here, if not inclusion) then we could look at the options. Thanks for your thoughts!

**Comment by pablobacho** [comment]
That is understandable. I just thought it could be easier for a newcomer, but it is not that important. If I end up making a wrapper I will definitely share it back. Thanks!
