### ISSUE TITLE
The library does not work correctly, no valid temperature readings.

### ISSUE THREAD

**Issue by lafar6502** [DavidAntliff/esp32-ds18b20#8]
So, with same wiring, with external power (no parasitic mode) the same sensor works on Arduino but does not work on ESP32 with your library.
On Arduino i'm using DallasTemperature library and it works solid, reliably every time. With esp32 board - no way, i cant get a reading.

The problem is i have no idea what goes wrong. The wiring is correct because onewire detects the sensor and initializes it, but reading the temperature doesnt work. The sensor always returns 85 degrees celcius (which is the 'default' value returned by dallas  in case of setup problems). 
My code for initialization and reading of sensors: 
https://github.com/lafar6502/esp_playground/blob/master/main/temp_sensors.c

Another thing - your example doesn't work either. It doesn't even detect the sensor. 
No idea why, basically my code is almost exactly the same as in your example, but i suspect some differences in build/compilation/linking? Tried modifying your example in various ways but no success, sensor is not found at all. Sorry i cant put more information in because there's no more information available to me - i have no idea how to diagnose the problem and i cant find any issue with my side of things - wiring is verified, checked with Arduino, code is basically borrowed from your example. And example is not working out of the box. My board is esp32-wrover

**Comment by DavidAntliff** [comment]
It sounds suspicious that it works with Arduino but not my code. What Arduino board are you using? Have you tried Arduino on the ESP32?

I haven't had anyone report a similar problem to date, but maybe something has come up in the IDF. Which version of the IDF are you compiling with?

Can you turn on debugging? Set this in your main function:

```
    esp_log_level_set("*", ESP_LOG_DEBUG);
```

You might need to enable run-time debugging in `make menuconfig` too (set default Log level to DEBUG).

Can you try a different pin too? I know it's obvious but please double-check you have specified the correct pin.

Do you have a logic analyser handy?

**Comment by DavidAntliff** [comment]
Just a thought - a few of the pins (34, 35, 36, 39) on the ESP32 are input-only, so can't be used with the One-Wire Bus as it has to operate as both input and output. Please check you aren't using one of those.

**Comment by lafar6502** [comment]
Hi David
tested this with another library on ESP-IDF - that one: https://github.com/UncleRus/esp-idf-lib
and the effect is exactly the same - sensor is detected, but reads 85C always.
Arduino - i'm using various boards, tested that sensor with pro mini 3.3v/8mhz, but have also worked with mega 2560.
Pins - i used pin 5, also pin 19 - same situation. For some strange reason it didnt find the sensor when using pin 17.
I have logic analyzer, but it's still in the box and never used that, so i'm not sure if i know how to debug anything. Maybe you can point me to some instructions..
I suspect the problem might be with the communication for requesting the read (you send 0x44 on the bus as i figured out from the code) - and only because 85C is the default value read from sensor when you don't request the conversion.
anyway, im bit tired and frustrated now because this small thing from hell was eating my time without any reward, but when i recover a little i'll do some debugging.
my idf: ESP-IDF v4.2-dev-674-g640c7c510-dirty
(this 'dirty' thing looks worrisome)

**Comment by lafar6502** [comment]
my debug output:
Hello world!
 gpio 5
D (2970) owb_rmt: owb_rmt_initialize: gpio_num: 5, tx_channel: 1, rx_channel: 0
D (2970) rmt: Rmt Tx Channel 1|Gpio 5|Sclk_Hz 80000000|Div 80|Carrier_Hz 0|Duty 0
D (2970) intr_alloc: Connected src 47 to int 13 (cpu 0)
D (2980) rmt: Rmt Rx Channel 0|Gpio 5|Sclk_Hz 80000000|Div 80|Thresold 77|Filter 30
D (2980) owb: use_crc 1
owb init owb 0x3ffb3590, driver 0x3ffb1284
Find devices:
D (2990) owb_rmt: _is_present 1
  0 : 8a01191c09472b28
Found 1 device
D (3020) ds18b20: malloc 0x3ffb4d5c
D (3020) ds18b20: scratchpad read 5 bytes: 
D (3020) owb_rmt: _is_present 1
D (3030) ds18b20: Resolution read as 10
D (3030) ds18b20: use_crc 1
D (3030) ds18b20: scratchpad read 5 bytes: 
D (3030) owb_rmt: _is_present 1
D (3050) ds18b20: configuration value 0x3f
D (3050) owb_rmt: _is_present 1
D (3060) ds18b20: scratchpad write 3 bytes:
D (3060) ds18b20: scratchpad read 5 bytes: 
D (3060) owb_rmt: _is_present 1
D (3070) ds18b20: Resolution set to 10 bits
requesting read. devs 1, owb 0x3ffb3590, driver 0x3ffb1284
D (3070) owb_rmt: _is_present 1
gpio task createdD (3070) efuse: coding scheme 0
I (3070) gpio: GPIO[18]| InputEn: 1| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
D (3090) efuse: In EFUSE_BLK0__DATA3_REG is used 1 bits starting with 15 bit
gp initD (3090) efuse: coding scheme 0
D (3100) efuse: In EFUSE_BLK0__DATA5_REG is used 1 bits starting with 20 bit
This is esp32 chip with 2 CPU cores, WiFi/BT/BLE, silicon revision 1, 2MB external flash
gp 18 - l0
trying to read. devs 1, owb 0x3ffb3590, driver 0x3ffb1284
D (4110) owb_rmt: _is_present 1
D (4110) ds18b20: divisor 4
D (4110) ds18b20: wait for conversion: 187.500 ms, 19 ticks
D (4300) owb_rmt: _is_present 1
D (4310) owb: crc 0xdb, len 9
D (4310) owb: crc 0x48, len 8
D (4310) owb: crc 0xe2, len 7
D (4310) owb: crc 0xce, len 6
D (4310) owb: crc 0x2a, len 5
D (4310) owb: crc 0x68, len 4
D (4320) owb: crc 0x58, len 3
D (4320) owb: crc 0x84, len 2
D (4320) owb: crc 0x00, len 1
D (4330) ds18b20: temp_LSB 0x50, temp_MSB 0x05, temp 85.000000
dev 0 TEMP 85.0
gp 18 - l1
trying to read. devs 1, owb 0x3ffb3590, driver 0x3ffb1284
D (5330) owb_rmt: _is_present 1
D (5330) ds18b20: divisor 4
D (5330) ds18b20: wait for conversion: 187.500 ms, 19 ticks
D (5520) owb_rmt: _is_present 1
D (5530) owb: crc 0xdb, len 9
D (5530) owb: crc 0x48, len 8
D (5530) owb: crc 0xe2, len 7
D (5530) owb: crc 0xce, len 6
D (5530) owb: crc 0x2a, len 5
D (5530) owb: crc 0x68, len 4
D (5540) owb: crc 0x58, len 3
D (5540) owb: crc 0x84, len 2
D (5540) owb: crc 0x00, len 1
D (5550) ds18b20: temp_LSB 0x50, temp_MSB 0x05, temp 85.000000
dev 0 TEMP 85.0
gp 18 - l0
trying to read. devs 1, owb 0x3ffb3590, driver 0x3ffb1284
D (6550) owb_rmt: _is_present 1
D (6550) ds18b20: divisor 4
D (6550) ds18b20: wait for conversion: 187.500 ms, 19 ticks
D (6740) owb_rmt: _is_present 1
D (6750) owb: crc 0xdb, len 9
D (6750) owb: crc 0x48, len 8
D (6750) owb: crc 0xe2, len 7
D (6750) owb: crc 0xce, len 6
D (6750) owb: crc 0x2a, len 5
D (6750) owb: crc 0x68, len 4
D (6760) owb: crc 0x58, len 3
D (6760) owb: crc 0x84, len 2
D (6760) owb: crc 0x00, len 1
D (6770) ds18b20: temp_LSB 0x50, temp_MSB 0x05, temp 85.000000
dev 0 TEMP 85.0
gp 18 - l1
trying to read. devs 1, owb 0x3ffb3590, driver 0x3ffb1284
D (7770) owb_rmt: _is_present 1

**Comment by DavidAntliff** [comment]
Thanks, I'll examine this soon. Just to make it easier to read, can you please edit your comment and add three backticks like this: ``` around the entire text, both top and bottom. That will format it as fixed monospaced font, like this:

```
D (6750) owb: crc 0xce, len 6
D (6750) owb: crc 0x2a, len 5
D (6750) owb: crc 0x68, len 4
D (6760) owb: crc 0x58, len 3
D (6760) owb: crc 0x84, len 2
D (6760) owb: crc 0x00, len 1
```

**Comment by DavidAntliff** [comment]
So from what I can tell, the code is detecting your device, and it's also successfully configuring it. The transactions are protected by a CRC check, so there's no errors on the wire either. But the temperature being read back is clearly incorrect.

Can you run _my_ DS18B20 example with this debugging enabled too, with the correct pin configured? Then we can compare the logs against each other.

**Comment by lafar6502** [comment]
ok here's the output from your example
a mystery: did not work on GPIO4 - no device found. changed to GPIO5 -then it worked.
At this point i dont even want to know why.

```
D (952) heap_init: New heap initialised at 0x3ffe0440
D (962) heap_init: New heap initialised at 0x3ffe4350
D (962) intr_alloc: Connected src 16 to int 12 (cpu 0)
D (2972) owb_rmt: owb_rmt_initialize: gpio_num: 5, tx_channel: 1, rx_channel: 0
D (2972) rmt: Rmt Tx Channel 1|Gpio 5|Sclk_Hz 80000000|Div 80|Carrier_Hz 0|Duty 254
D (2972) intr_alloc: Connected src 47 to int 13 (cpu 0)
D (2972) rmt: Rmt Rx Channel 0|Gpio 5|Sclk_Hz 80000000|Div 80|Thresold 77|Filter 30
D (2982) owb: use_crc 1
Find devices pin 5:
D (2992) owb_rmt: _is_present 1
  0 : 8a01191c09472b28
Found 1 device
D (3022) owb_rmt: _is_present 1
D (3022) owb: crc 0xe1, len 8
D (3022) owb: crc 0xb4, len 7
D (3022) owb: crc 0x96, len 6
D (3022) owb: crc 0x50, len 5
D (3032) owb: crc 0xe5, len 4
D (3032) owb: crc 0xd7, len 3
D (3032) owb: crc 0x8a, len 2
D (3032) owb: crc 0x00, len 1
D (3042) owb: rom_code 8a01191c09472b28
Single device 8a01191c09472b28 present
D (3042) ds18b20: malloc 0x3ffb4d5c
Single device optimisations enabled
D (3052) ds18b20: scratchpad read 5 bytes: 
D (3062) owb_rmt: _is_present 1
D (3062) ds18b20: Resolution read as 10
D (3062) ds18b20: use_crc 1
D (3072) ds18b20: scratchpad read 5 bytes: 
D (3072) owb_rmt: _is_present 1
D (3082) ds18b20: configuration value 0x7f
D (3082) owb_rmt: _is_present 1
D (3082) ds18b20: scratchpad write 3 bytes:
D (3092) ds18b20: scratchpad read 5 bytes: 
D (3092) owb_rmt: _is_present 1
D (3102) ds18b20: Resolution set to 12 bits
D (3102) owb_rmt: _is_present 1
D (3102) ds18b20: divisor 1
D (3102) ds18b20: wait for conversion: 750.000 ms, 75 ticks
D (3862) owb_rmt: _is_present 1
D (3862) owb: crc 0xdb, len 9
D (3862) owb: crc 0x48, len 8
D (3862) owb: crc 0xe2, len 7
D (3862) owb: crc 0xce, len 6
D (3862) owb: crc 0x2a, len 5
D (3872) owb: crc 0x68, len 4
D (3872) owb: crc 0x58, len 3
D (3872) owb: crc 0x84, len 2
D (3882) owb: crc 0x00, len 1
D (3882) ds18b20: temp_LSB 0x50, temp_MSB 0x05, temp 85.000000

Temperature readings (degrees C): sample 1
  0: 85.0    0 errors
D (4102) owb_rmt: _is_present 1
D (4102) ds18b20: divisor 1
D (4102) ds18b20: wait for conversion: 750.000 ms, 75 ticks
D (4852) owb_rmt: _is_present 1
D (4852) owb: crc 0xdb, len 9
D (4852) owb: crc 0x48, len 8
D (4852) owb: crc 0xe2, len 7
D (4852) owb: crc 0xce, len 6
D (4852) owb: crc 0x2a, len 5
D (4862) owb: crc 0x68, len 4
D (4862) owb: crc 0x58, len 3
D (4862) owb: crc 0x84, len 2
D (4872) owb: crc 0x00, len 1
D (4872) ds18b20: temp_LSB 0x50, temp_MSB 0x05, temp 85.000000

Temperature readings (degrees C): sample 2
  0: 85.0    0 errors
D (5102) owb_rmt: _is_present 1
D (5102) ds18b20: divisor 1
D (5102) ds18b20: wait for conversion: 750.000 ms, 75 ticks
D (5852) owb_rmt: _is_present 1
D (5852) owb: crc 0xdb, len 9
D (5852) owb: crc 0x48, len 8
D (5852) owb: crc 0xe2, len 7
D (5852) owb: crc 0xce, len 6
D (5852) owb: crc 0x2a, len 5
D (5862) owb: crc 0x68, len 4
D (5862) owb: crc 0x58, len 3
D (5862) owb: crc 0x84, len 2
D (5872) owb: crc 0x00, len 1
D (5872) ds18b20: temp_LSB 0x50, temp_MSB 0x05, temp 85.000000

Temperature readings (degrees C): sample 3
  0: 85.0    0 errors
D (6102) owb_rmt: _is_present 1
D (6102) ds18b20: divisor 1
D (6102) ds18b20: wait for conversion: 750.000 ms, 75 ticks
D (6852) owb_rmt: _is_present 1
D (6852) owb: crc 0xdb, len 9
D (6852) owb: crc 0x48, len 8
D (6852) owb: crc 0xe2, len 7
D (6852) owb: crc 0xce, len 6
D (6852) owb: crc 0x2a, len 5
D (6862) owb: crc 0x68, len 4
D (6862) owb: crc 0x58, len 3
D (6862) owb: crc 0x84, len 2
D (6872) owb: crc 0x00, len 1
D (6872) ds18b20: temp_LSB 0x50, temp_MSB 0x05, temp 85.000000

Temperature readings (degrees C): sample 4
  0: 85.0    0 errors
D (7102) owb_rmt: _is_present 1
D (7102) ds18b20: divisor 1
D (7102) ds18b20: wait for conversion: 750.000 ms, 75 ticks
D (7852) owb_rmt: _is_present 1
D (7852) owb: crc 0xdb, len 9
D (7852) owb: crc 0x48, len 8
D (7852) owb: crc 0xe2, len 7
D (7852) owb: crc 0xce, len 6
D (7852) owb: crc 0x2a, len 5
D (7862) owb: crc 0x68, len 4
D (7862) owb: crc 0x58, len 3
D (7862) owb: crc 0x84, len 2
D (7872) owb: crc 0x00, len 1
D (7872) ds18b20: temp_LSB 0x50, temp_MSB 0x05, temp 85.000000

```

**Comment by lafar6502** [comment]
![image](https://user-images.githubusercontent.com/1706814/76709962-8ad50300-6703-11ea-9833-b907f6106830.png)

**Comment by DavidAntliff** [comment]
Ok, thanks for the logs. It looks like both programs are able to detect and communicate with the device properly (no CRC errors).

0x55/85 is the power-on reset value of the temperature register, so if it's not able to complete a conversion then it makes some sense that this value would remain. My first suspicion is that this is looking like a possible issue with the device or wiring. For example, there may not be enough current being supplied to the device (it runs at 3.3V, does your Arduino run at 5V or 3.3V?). Can you describe (or quickly draw) your circuit diagram please? How long is the wire to your DS18B20? What are you powering it with?

I'd suggest trying a few things - a different DS18B20, shorter wires, change the pull-up resistor value (what is it currently?). Are you using a diode for protection? Try with it removed.

Thanks for the logic analyser diagram, I'm not sure it shows the issue yet, but it will be a reference.

**Comment by DavidAntliff** [comment]
Also, try with a lower resolution (e.g. 9 bits) as that has a shorter conversion time, which might succeed if the current supply is an issue.

**Comment by lafar6502** [comment]
arduino - just tested on 3.3v, works flawlessly
wiring - impossible to get wrong, especially so many times ... 
switched resolution to 10 bit and heres the output
but im afraid it adjusts the timing accordingly

```
D (0) intr_alloc: Connected src 25 to int 2 (cpu 1)
I (0) cpu_start: Starting scheduler on APP CPU.
D (952) heap_init: New heap initialised at 0x3ffe0440
D (962) heap_init: New heap initialised at 0x3ffe4350
D (962) intr_alloc: Connected src 16 to int 12 (cpu 0)
D (2972) owb_rmt: owb_rmt_initialize: gpio_num: 5, tx_channel: 1, rx_channel: 0
D (2972) rmt: Rmt Tx Channel 1|Gpio 5|Sclk_Hz 80000000|Div 80|Carrier_Hz 0|Duty 254
D (2972) intr_alloc: Connected src 47 to int 13 (cpu 0)
D (2972) rmt: Rmt Rx Channel 0|Gpio 5|Sclk_Hz 80000000|Div 80|Thresold 77|Filter 30
D (2982) owb: use_crc 1
Find devices pin 5:
D (2992) owb_rmt: _is_present 1
  0 : 8a01191c09472b28
Found 1 device
D (3022) owb_rmt: _is_present 1
D (3022) owb: crc 0xe1, len 8
D (3022) owb: crc 0xb4, len 7
D (3022) owb: crc 0x96, len 6
D (3022) owb: crc 0x50, len 5
D (3032) owb: crc 0xe5, len 4
D (3032) owb: crc 0xd7, len 3
D (3032) owb: crc 0x8a, len 2
D (3032) owb: crc 0x00, len 1
D (3042) owb: rom_code 8a01191c09472b28
Single device 8a01191c09472b28 present
D (3042) ds18b20: malloc 0x3ffb4d5c
Single device optimisations enabled
D (3052) ds18b20: scratchpad read 5 bytes: 
D (3062) owb_rmt: _is_present 1
D (3062) ds18b20: Resolution read as 10
D (3062) ds18b20: use_crc 1
D (3072) ds18b20: scratchpad read 5 bytes: 
D (3072) owb_rmt: _is_present 1
D (3082) ds18b20: configuration value 0x3f
D (3082) owb_rmt: _is_present 1
D (3082) ds18b20: scratchpad write 3 bytes:
D (3092) ds18b20: scratchpad read 5 bytes: 
D (3092) owb_rmt: _is_present 1
D (3102) ds18b20: Resolution set to 10 bits
D (3102) owb_rmt: _is_present 1
D (3102) ds18b20: divisor 4
D (3102) ds18b20: wait for conversion: 187.500 ms, 19 ticks
D (3302) owb_rmt: _is_present 1
D (3302) owb: crc 0xdb, len 9
D (3302) owb: crc 0x48, len 8
D (3302) owb: crc 0xe2, len 7
D (3302) owb: crc 0xce, len 6
D (3302) owb: crc 0x2a, len 5
D (3312) owb: crc 0x68, len 4
D (3312) owb: crc 0x58, len 3
D (3312) owb: crc 0x84, len 2
D (3322) owb: crc 0x00, len 1
D (3322) ds18b20: temp_LSB 0x50, temp_MSB 0x05, temp 85.000000

Temperature readings (degrees C): sample 1
  0: 85.0    0 errors
D (4102) owb_rmt: _is_present 1
D (4102) ds18b20: divisor 4
D (4102) ds18b20: wait for conversion: 187.500 ms, 19 ticks
D (4292) owb_rmt: _is_present 1
D (4292) owb: crc 0xdb, len 9
D (4292) owb: crc 0x48, len 8
D (4292) owb: crc 0xe2, len 7
D (4292) owb: crc 0xce, len 6
D (4292) owb: crc 0x2a, len 5
D (4302) owb: crc 0x68, len 4
D (4302) owb: crc 0x58, len 3
D (4302) owb: crc 0x84, len 2
D (4312) owb: crc 0x00, len 1
D (4312) ds18b20: temp_LSB 0x50, temp_MSB 0x05, temp 85.000000

Temperature readings (degrees C): sample 2
  0: 85.0    0 errors
D (5102) owb_rmt: _is_present 1
D (5102) ds18b20: divisor 4
D (5102) ds18b20: wait for conversion: 187.500 ms, 19 ticks
D (5292) owb_rmt: _is_present 1
D (5292) owb: crc 0xdb, len 9
D (5292) owb: crc 0x48, len 8
D (5292) owb: crc 0xe2, len 7
D (5292) owb: crc 0xce, len 6
D (5292) owb: crc 0x2a, len 5
D (5302) owb: crc 0x68, len 4
D (5302) owb: crc 0x58, len 3
D (5302) owb: crc 0x84, len 2
D (5312) owb: crc 0x00, len 1
D (5312) ds18b20: temp_LSB 0x50, temp_MSB 0x05, temp 85.000000

Temperature readings (degrees C): sample 3
  0: 85.0    0 errors
D (6102) owb_rmt: _is_present 1
D (6102) ds18b20: divisor 4
D (6102) ds18b20: wait for conversion: 187.500 ms, 19 ticks
D (6292) owb_rmt: _is_present 1
D (6292) owb: crc 0xdb, len 9
D (6292) owb: crc 0x48, len 8
D (6292) owb: crc 0xe2, len 7
D (6292) owb: crc 0xce, len 6
D (6292) owb: crc 0x2a, len 5
D (6302) owb: crc 0x68, len 4
D (6302) owb: crc 0x58, len 3
D (6302) owb: crc 0x84, len 2
D (6312) owb: crc 0x00, len 1
D (6312) ds18b20: temp_LSB 0x50, temp_MSB 0x05, temp 85.000000
```

**Comment by lafar6502** [comment]
So here's a recording from the logic analyzer. It can be seen the timing is changed (after first communication there's another one with some delay - probably the conversion results are read).
let me know if these are useful or not, i have no idea how to use the logic analyzer program properly.

edit: i think the first short burst is requesting the conversion, the next one after some delay (depending on bit resolution) is reading of the conversion results.

[samples_for_10_and_12_bit.zip](https://github.com/DavidAntliff/esp32-ds18b20/files/4335030/samples_for_10_and_12_bit.zip)

**Comment by DavidAntliff** [comment]
With the Arduino, where are you drawing 3.3V from? Then with the ESP32, where do you get the 3.3V from? Do you have an external power supply you can use? Thing is, the DS18B20 is pretty low-powered anyway so this seems unlikely to be an issue, but best to check.

From the logs it shows that the conversion process is operating, reaches the end, and then the conversion register is read. Because there's no CRC errors, the communication with the device (that you see on your analyser) is working correctly, so I don't think that's the problem. 

One thing you can check - with 12-bit resolution, the conversion should take 750ms, so you can use your analyser to see that the device holds the OneWire high for at least this duration, before releasing it, and then the ESP32 should read the conversion register.

Thanks for the logic analyser files, but unfortunately they are in a proprietary binary format. Is there an "Export" function in your software to get CSV or text or something else?

**Comment by lafar6502** [comment]
look at this
with 12 bit the debug says it should wait for 750 ms
`D (5102) ds18b20: divisor 1

`D (5102) ds18b20: wait for conversion: 750.000 ms, 75 ticks
and in the logic record
![image](https://user-images.githubusercontent.com/1706814/76710279-7e05de80-6706-11ea-949e-fe0b9a16f599.png)
the distance between the requesting of conversion and reading data is 748 ms

**Comment by DavidAntliff** [comment]
Ah, you beat me to it. That does seem like it might be a little short. However, the line is held by the device during conversion, so when it goes low, the device is signalling that it has finished. 748 is about 750ms as per datasheet, so that's probably OK.

**Comment by lafar6502** [comment]
with 10 bit it's 187 ms
![image](https://user-images.githubusercontent.com/1706814/76710309-c1f8e380-6706-11ea-8170-a0d2d6764322.png)

**Comment by lafar6502** [comment]
btw, you can download logic analyzer program from Saleae for free and use it for opening the recorded files, this way i think it's easier than CSV
https://www.saleae.com/downloads/
and regarding my power supply -it's from the board, powered via USB, both for arduino and esp32
also i tried 4.7K and 3.3K pull up resistor on the data line

**Comment by lafar6502** [comment]
and here is the recorded communication with arduino. I made it a bit similar - read celcius temperature every 1 second. But the data transfers look very different, much longer for sure.
[Arduino_temp_read_correct.zip](https://github.com/DavidAntliff/esp32-ds18b20/files/4335068/Arduino_temp_read_correct.zip)
probably because it works a bit different, first of all device address is transferred (no optimization for single device) and apart from that there's no quiet waiting period - it keeps transmitting zeros thru all conversion time. But gets a correct reading.

**Comment by DavidAntliff** [comment]
Hmm, maybe the timing tolerance for this particular device is lower than average. I'll try the Saleae software when I get a chance. Thank you for all the info. I don't have a solution for you right now, but I'll continue to think about it, and let you know if I have any ideas. Something is obviously slightly different because my DS18B20 devices (I have four) seem to work OK, individually and together on the bus.

In the meantime, you could add an artificial delay of a few hundred milliseconds between `ds18b20_wait_for_conversion` and `ds18b20_read_temp` calls, to see if that helps.

**Comment by DavidAntliff** [comment]
Do you have a second device? Can you try with two devices on the bus?

**Comment by lafar6502** [comment]
added 20 ms delay before read (for 9 bit res)
et voila, it gets the right temperature:

```
D (23242) owb: crc 0x00, len 1
D (23242) ds18b20: temp_LSB 0x80, temp_MSB 0x01, temp 24.000000

Temperature readings (degrees C): sample 21
  0: 24.0    0 errors
D (24102) owb_rmt: _is_present 1
D (24102) ds18b20: divisor 8
D (24102) ds18b20: wait for conversion: 93.750 ms, 10 ticks
D (24222) owb_rmt: _is_present 1
D (24222) owb: crc 0x4e, len 9
D (24222) owb: crc 0x07, len 8
D (24222) owb: crc 0xe5, len 7
D (24222) owb: crc 0x4d, len 6
D (24232) owb: crc 0x67, len 5
D (24232) owb: crc 0xd3, len 4
D (24232) owb: crc 0x69, len 3
D (24232) owb: crc 0x64, len 2
D (24242) owb: crc 0x00, len 1
D (24242) ds18b20: temp_LSB 0x88, temp_MSB 0x01, temp 24.500000

Temperature readings (degrees C): sample 22
  0: 24.5    0 errors
D (25102) owb_rmt: _is_present 1
D (25102) ds18b20: divisor 8
D (25102) ds18b20: wait for conversion: 93.750 ms, 10 ticks
D (25222) owb_rmt: _is_present 1
D (25222) owb: crc 0x11, len 9
D (25222) owb: crc 0x9d, len 8
D (25222) owb: crc 0x8a, len 7
D (25222) owb: crc 0x69, len 6
D (25232) owb: crc 0x25, len 5
D (25232) owb: crc 0x29, len 4
D (25232) owb: crc 0x63, len 3
D (25232) owb: crc 0x1a, len 2
D (25242) owb: crc 0x00, len 1
D (25242) ds18b20: temp_LSB 0x90, temp_MSB 0x01, temp 25.000000
```
many thanks for your help, i think we're not done yet but at least there's some nice result
Can you please think why this extra delay might be needed and how many milliseconds need to be added to be safe? Or best, make adjustments to the library so there's no need for any such tricks.
My experience with ESP32 so far : bravely solving problems unknown to any other microcontrollers.

**Comment by DavidAntliff** [comment]
Glad to hear you've made some progress - thanks for sticking with it.

Can you try an experiment for me, please? Can you try various delays and see if you can find the delay that results in a roughly 50/50 success rate? I.e. try to find the extra delay needed to "just" get it working again. I've never seen this happen with any DS18B20 devices I own, so I'm wondering if your device is somehow slightly out-of-spec (and works with Arduino because it's much less precise timing-wise).

**Comment by DavidAntliff** [comment]
In the meantime I'll investigate adding a check for the data line still low (driven from the device) and extending the wait if required - maybe your ESP32 is running slightly fast (crystal variation) and doesn't quite wait long enough. I may look at some kind of interrupt-based wait also.

**Comment by lafar6502** [comment]
David, from what i understood from the code, your library does not wait for the sensor to signal conversion ready.  The _wait_for_conversion function just waits for the calculated number of milliseconds and then reads the data regardless of the bus state. So this leads us back to the timing diagram for 12 bit - the library tells esp32 to sleep for 750ms but apparently my board has some different idea about it and wakes 2ms earlier. This is probably some issue with lower level libraries and may depend on version of the sdk. But the way _wait_for_conversion works bothers me a bit, if you say that the sensor should signal readiness why not make use of this signaling?
The other possibility is that i dont see the whole picture and the synchronization happens somewhere else?

**Comment by lafar6502** [comment]
and btw did some testing in the office, but this time using some clone of nodemcu esp32-s board. At first added some delay before read call, but it appears delay is not necessary - reads were ok without it as well.
Then added second sensor and it also works OK for two.

**Comment by DavidAntliff** [comment]
Yep, I mentioned the wait for conversion thing a little earlier - it should have a final check (and rewait loop). I'll need to extend the OWB library to support this. One reason I didn't implement this originally is because it doesn't work for parasitic power mode (which this library doesn't support, but I had planned to support it when I started writing it). I'll also need to think carefully about how this will work with multiple devices on the bus, although since the last device to complete the conversion will release the bus, it should work.

I'll leave this issue open until I have addressed this properly. Thanks again for your feedback, and patience. 

P.S. your board may be running slightly too fast due to a clock generation issue. If you're able to measure the clock frequency you may be able to determine if this is the cause.

Can you try that little experiment I mentioned above sometime, please? The results could be very interesting.

**Comment by DavidAntliff** [comment]
@lafar6502 I've implemented a check for conversion-complete signal (from all devices on the bus). My local testing suggests that it works, with a conversion duration of around 660ms. If you enable DEBUG on the `ds18b20` component it should tell you what your conversion duration is. I've set a timeout at 110% of the datasheet value, to avoid locking up.

If you can confirm that this works with your device, I will merge the changes to the main line.

https://github.com/DavidAntliff/esp32-ds18b20-example/pull/8

**Comment by lafar6502** [comment]
hi David, will do that when possible, quite busy with other stuff now. thanks!

**Comment by lafar6502** [comment]
hi, returned to it recently but i couldn't even get the sensor detected when running your example. I switched esp-idf version to the most recent master. And i think i also have some clock/timing issues on the board because i cant get accurate time measurements - seems off by 20-30%. This may be causing communication problems and i have to figure this out first.

**Comment by DavidAntliff** [comment]
@lafar6502 no problem - I'll probably merge the improvement at some point anyway, but still keen to hear back from you eventually, once you have a chance to test :)  Thanks again for reporting.
